Feature/make the desktop version
ayaderaghul/portfolio pull request #6
Opened 2023-01-21 02:31 UTC by ayaderaghul

- Add content to index.html
- Add comments to html file
- Add style to styles.css

2023-01-21 04:19 UTC, AbayomiOlaoye requested changes
Hi @ayaderaghul :bow: , 

Good job with this milestone so far!
There are just few more issues to work on before moving onto the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 04:19 UTC, AbayomiOlaoye commented on index.html
>              </section>
- [x] While you have made a great effort here, I think you need to give your great design a second look.  Currently, there's a great `overflow` on the `x-axis` that needs to be checked and corrected to ensure a good design implementation.
- [x] The `overflow` makes the content on the page very difficult to read.
- [x] The `background-image` has too much noise or distortion. I recommend that you check again to ensure that you have imported the correct image using the right `background` properties.
- Kindly consider the two designs 👇

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/213841164-cb2b4d5d-f217-4fdd-99c9-b138fb8fdeb7.png)|![image](https://user-images.githubusercontent.com/99715640/213841183-b087590b-7157-46fa-bc52-c2c32e9a6c7a.png)|

2023-01-21 04:19 UTC, AbayomiOlaoye commented on index.html
> +                </section>
- [ ] You have eyes for great designs, and I believe that this is why you chose this template :smile: :clap: but right now, I suggest that you check all your project cards for responsiveness, correct `background` color, correct `spacing` elements like margin and padding. Your project card seems to have the wrong background color values. Please check the figma design and redesign. This will go a long way improving your designs.

- Attached are images of both designs:

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/213842238-e9ba731a-9963-4d86-9f69-0fa674cd50c1.png)|![image](https://user-images.githubusercontent.com/99715640/213842267-1e3ed790-7f43-42d0-91c8-fc402cbf338f.png)|

- [x] Inspecting your `grid-gap` , I see a spacing of 350px while the requirement only has 130px. Please to make sure your design is close to the benchmark as possible.
- [x] Your `contact` and `about me` sections have margins and padding as against the Figma design, please correct this so that we remain consistent with the design.
- [x] With close observation, you will see that `contact` and `about me` sections have some `rounded edges` - implementing this will make your work really nice.

2023-01-21 04:19 UTC, AbayomiOlaoye commented on index.html
>                  <div class="contact-container">
- [ ] Kindly invest some time here too, to fix some bugs that shields your design prowess. I can't find your button, the background images is not showing and I think you need to work on some elements e.g. `width`, `padding`, `margin`, etc. as revealed with the image below:

![image](https://user-images.githubusercontent.com/99715640/213843024-1909cf5a-031a-4da2-b0a6-8b837908ad67.png)

2023-01-21 22:35 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @ayaderaghul , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 22:35 UTC, joskalenda commented on style.css
> +  .body {
- [ ] As mentioned by the previous reviewer, please make sure you fix this sliding effect, your current design is moving from left to right and that makes your app behave badly, please fix it

![5](https://user-images.githubusercontent.com/77843050/213889519-486fcbd0-449b-40e5-b5f9-7dee98e72289.gif)

- [ ] Your Desktop code should not break down the former mobile version design, make sure both your desktop and mobile version work fine, and see how it behave currently

![5](https://user-images.githubusercontent.com/77843050/213889637-671fcc40-492b-4e7c-b3d4-1b23448f70bb.gif)

2023-01-27 17:25 UTC, huseyinbiyik requested changes
Hi @ayaderaghul,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Required Changes ♻️
- Unfortunately I couldn't pick the related lines since they were merged. Good job with the overflowing issue on the heading section. But let's make sure we don't break the mobile version of our work.
This image is your last branch contact-form
<img width="389" alt="Screenshot 2023-01-27 at 8 10 46 PM" src="https://user-images.githubusercontent.com/25887253/215151934-fba70bf2-e4f0-4124-bd70-3e1ccecc492c.png">

This one is the current one:
<img width="389" alt="Screenshot 2023-01-27 at 8 11 17 PM" src="https://user-images.githubusercontent.com/25887253/215152029-59092f66-8b47-4cd3-bb84-091657060e63.png">

Kindly fix the social icons overlaying issue.




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Perfect job but you can remove the top section, it is not a part of the project requirements.
<img width="389" alt="Screenshot 2023-01-27 at 8 12 05 PM" src="https://user-images.githubusercontent.com/25887253/215152323-8ca8835e-8712-496f-b4cf-a8b0f1711bb4.png">

- [OPTIONAL] Good job with the overflowing issue on the desktop version but let's fix the overflowing issue on mobile version.
![Screen Recording 2023-01-27 at 8 12 29 PM](https://user-images.githubusercontent.com/25887253/215152769-1b00c5a9-1a6d-4e1a-adc6-73b715068895.gif)∂

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 15:09 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @ayaderaghul, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/894d22fdf31aac32d1cd488fc22318df1eea3204fa6d0129c3d61a99f137ce2d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336b75536f3734345549504a6a634a55456e2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 15:09 UTC, Qoosim commented on style-desktop.css
> +
- [OPTIONAL] At the breakpoints 768px, some sections are not properly positioned at the center of the page. Kindly look into them and fix.

 
[your-page-desktop.webm](https://user-images.githubusercontent.com/26597432/215273421-893c29b7-b96a-4b08-a67e-433877b62558.webm)

2023-01-28 15:09 UTC, Qoosim commented on output/style.css
>    flex-direction: column;
- [OPTIONAL] At the breakpoints 767px,  background image at your headline section does not extend to cover the whole width of that section. 
- Also, the project information of each projects is not also responsive at that breakpoints. They seem to be fixed to a particular width at that breakpoints. Kindly look into them and fix them.

[your-page-blank-space.webm](https://user-images.githubusercontent.com/26597432/215273688-45687bd6-352e-48dd-b642-866faecf58c6.webm)

2023-01-28 15:09 UTC, Qoosim commented on output/style.css
> +  margin-top: -30px;
- [OPTIONAL] The left top curve on the blue background for the contact-me section is missing at breakpoints 767px. Kindly look into it and fix.

![your-form-area](https://user-images.githubusercontent.com/26597432/215273877-24616887-fa68-4418-bf5b-8382ac6880ea.png)

2023-01-30 09:43 UTC, merged